FROM debian:latest

RUN apt update -y && apt install -y curl python3-pip openssh-client scdaemon sshpass

RUN pip3 install ansible --break-system-packages

RUN useradd mgmt -m

ENV ANSIBLE_CONFIG=/work/config/ansible.cfg

RUN mkdir /work && chown mgmt:mgmt /work

USER mgmt

WORKDIR /work
