- name: install docker
  hosts: all
  remote_user: root
  roles:
    - docker

- name: install bind and configure
  hosts: dns
  remote_user: root
  roles:
    - dns

- name: install and configure mailcow
  hosts: mail
  remote_user: root
  roles:
    - docker
    - mail
