- name: install dependencies
  ansible.builtin.apt:
    name: gpg
    state: "present"
- name: add docker keyring
  ansible.builtin.apt_key:
    keyring: "{{ var_role_docker_repokey_keyring }}"
    url: "{{ var_role_docker_repokey_url }}"
    state: "present"

- name: add docker repo
  ansible.builtin.apt_repository:
    repo: "{{ var_role_docker_repo_repostring }}"
    filename: "{{ var_role_docker_repo_filename }}"
    state: "present"

- name: install docker
  ansible.builtin.apt:
    name: docker.io docker-compose-plugin
    update_cache: true
    state: "present"
